CREATE TABLE SNAKE_CASE_TABLE (
  VARCHAR_COLUMN1 VARCHAR2(2) NOT NULL
  , VARCHAR_COLUMN2 VARCHAR2(1) NOT NULL
  , DATE_COLUMN DATE NOT NULL
  , VARCHAR_COLUMN_MEANS_DATE VARCHAR2(8) NOT NULL
  , DECIMAL_COLUMN NUMBER(12, 5)
  , NUMBER_COLUMN NUMBER(10, 0) NOT NULL
  , CONSTRAINT CAMEL_CASE_TABLE_PKC PRIMARY KEY (VARCHAR_COLUMN1,VARCHAR_COLUMN2)
) ;
